import "./globals.css";
import "./fanta.css"
import Head from "./head";
import AuthProvider from "@/context/AuthContext";



export const metadata = {
  title: "Da vinci diary | Easy But Inventive Notetaking",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head />
      <AuthProvider>
        <body>
            <div id="app">{children}</div>
            <div id="portal"></div>
        
        </body>
      </AuthProvider>
    </html>
  );
}
